JSON Schema propertyNames compatibility
aiven/karapace pull request #206
Opened 2021-04-29 15:11 UTC by tvainika

# About this change: What it does, why it matters

Fix `propertyNames` support: An object with `propertyNames` setting constraints on property names is still open ie. there are no limitations on property values for those.

Add separate test for object properties without `propertyNames` and fix test to match existing integration test.

2021-04-29 19:16 UTC, hackaugusto requested changes

2021-04-29 19:16 UTC, hackaugusto commented on tests/unit/test_json_schema.py
> +        msg=INCOMPATIBLE_READER_IS_CLOSED_AND_REMOVED_FIELD,
here the message should be `INCOMPATIBLE_READER_RESTRICTED_ACCEPTED_VALUES`

2021-04-29 19:16 UTC, hackaugusto commented on tests/unit/test_json_schema.py
> +        msg=COMPATIBILIY,
here the message should be `INCOMPATIBLE_READER_RESTRICTED_ACCEPTED_VALUES`

2021-04-29 19:16 UTC, hackaugusto commented on tests/unit/test_json_schema.py
> +        msg=COMPATIBILIY,
here the message should be `INCOMPATIBLE_READER_RESTRICTED_ACCEPTED_VALUES`

2021-04-30 08:16 UTC, tvainika commented
> Open is used to say if unknown properties are allowed, not if the existing ones have constraints in their values, i.e. if `additionalProperties` is not `false`

Maybe I used wording about openess wrongly, but yet schema with `propertyNames` constraint only makes backward compatible changes ie. adding _optional_ fields or deleting fields, not adding required fields. Thus the logic is fine, right?

2021-04-30 08:40 UTC, hackaugusto commented
> but yet schema with propertyNames constraint only makes backward compatible changes

I think adding `propertyNames` is backwards *incompatible*. Say the schema for the writer allows anything:
```
{}
```
This would allow a producer to generate `{"a":1}` and `{"b":2}`. Now the schema is updated with a `propertyNames`:
```
{
  "propertyNames": {
    "pattern": "^a+$"
  }
}
```
Now the value `{"b":2}` is not accepted anymore, thus a incompatible change.

2021-04-30 09:11 UTC, hackaugusto approved these changes

2021-04-30 09:11 UTC, merged

2021-04-30 09:50 UTC, tvainika commented
And to document for later usage, the implementation and the interpretation of schema compatibility now follows Confluent's Schema Registry's compatibility table even if it is written from Avro point of view (Avro does not have similar `propertyNames` pattern concept):
https://docs.confluent.io/platform/current/schema-registry/avro.html#compatibility-types