Add namespace patching if given Avro schema has invalid name for record type
aiven/karapace pull request #326
Opened 2022-02-04 14:16 UTC by jjaakola-aiven

Some generated Avro schemas have name `record` which is not allowed in
Python Avro parser. Patch this by adding a namespace to the root if it does not exist. This
creates enclosing namespace also for nested elements.

# Why this way
Java Avro parser accepts the `record` as a name. The specification only mentions that primitive types are not allowed to be used as name. Python Avro parser has stricter validation and rejects if `record` or any other complex type name is used.

As I know only of Flink generating such schemas and the issue is only on Avro type name `record` this PR does not try to mitigate any other complex types as name.

I think the patching by adding namespace if namespace does not exist is least intrusive option.

Other options are to:
* Add the patching to the name itself, `patched.name.record`.
* Change the name by uppercasing/adding lodash the first character, `_record`, `Record`.

One issue of this change I can think of is if Avro validation is made stricter to not allow type names at all. This renders the patching with namespaces invalid.

2022-02-04 15:43 UTC, RyanSkraba approved these changes
This LGTM -- nice fix!

You can add arbitrary JSON properties to an Avro schema, something like `schema_json["karapace.avro-3370-patched"] = true`.  This could help in the future if the behaviour changes... but I'm not really sure how it might be useful yet.

2022-02-06 12:28 UTC, hackaugusto commented
question: is this backwards compatible?

2022-02-07 15:53 UTC, RyanSkraba commented
> question: is this backwards compatible?

That's a good question.  This change modifies the schema being stored and returned, so it depends on how the schema is being used.  It looks promising:

Avro schema resolution [ignores namespaces](https://avro.apache.org/docs/current/spec.html#Schema+Resolution) when matching records.  If the user was using a common "reader" schema to read mismatched files, it should work transparently.  This is true if the reader schema is either the patched or unpatched schema.

Names and namespaces aren't ever present in serialized binary data, so the binary data serialized with the unpatched schema is always deserializable with the patched schema and vice versa.

However, if the user is comparing schema metadata, there could pose a problem.  For example writing Avro files from a Kafka topic using the unpatched schema, then switch to Karapace with the patched schema.  The two files will have different schema metadata, which might be unexpected.

It's tricky to know exactly what the issues might be without actually trying.  That being said, if this is a completely new job and installation, Karapace will have never accepted and served the unpatched schema.

2022-02-10 10:43 UTC, hackaugusto requested changes
Blocking merge for now. Considering doing the fix in the upstream library.

2022-03-16 10:20 UTC, RyanSkraba commented
I've asked for a 1.11.1 release on Avro, we should probably be seeing release candidates with the upstream fix in the next few weeks.

2022-08-10 09:39 UTC, kiliangrashoff commented
Avro 1.11.1 has been released, it would be nice if Karapace can be upgraded to it so the issue that this PR tried to fix is resolved (commenting here since I cannot find an issue for this).

2022-08-11 07:50 UTC, RyanSkraba commented
I've raised this issue #439 -- a PR will be incoming and we can close this.

The next version of Avro will accept the `record` name (https://issues.apache.org/jira/browse/AVRO-3370) but it will also forbid invalid enum defaults (https://issues.apache.org/jira/browse/AVRO-3229)

2023-02-10 09:24 UTC, jjaakola-aiven commented
Closing this PR, the Avro 1.11.x is used in Karapace.

2023-02-10 09:24 UTC, closed without merging