karapace: using context manager to ensure all resources are closed
aiven/karapace pull request #390
Opened 2022-04-08 17:17 UTC by hackaugusto

Just like https://github.com/aiven/karapace/pull/389 I found this while investigating the CI failures.

The test `tests/integration/test_master_coordinator.py::test_schema_request_forwarding`  had a server failures, where one server couldn't bind to the socket because of `address already in use` (I assume it was a linger socket). Because of that the main thread died, but the other threads kept running, and the worst one was the master coordinator, eventually the dead server became leader. The result was a leader node without a server, and when the follower forwarded the request to the master it failed with a connection error.

fixes #138

2022-04-11 12:45 UTC, hackaugusto commented on karapace/karapace.py
> -        self.app.on_shutdown.append(self.close_by_app)
This didn't really work. I _think_ the eventloop is closed when shutdown is called, if that is correct then the execution failed at some point in time, when running a task, and not everything was closed.

This PR consolidates all the cleanup in the base class, and uses `on_cleanup` instead, which works as expected.

2022-04-11 12:45 UTC, hackaugusto commented on karapace/kafka_rest_apis/__init__.py
> +            stack.push_async_callback(super().close)
Note: This works, I double checked by stepping through he execution

2022-04-21 05:36 UTC, tvainika requested changes
Seems that conflict resolution / rebase gone wrong with on extra partial commit here causing lint failure

With exit stack usage, I noticed order of close methods being called was being reversed. This was intentional / not relevant?

Also see one inline comment about spelling.

2022-04-21 05:36 UTC, tvainika commented on tests/integration/test_karapace.py
> +def test_regression_server_must_exist_on_exception(
```suggestion
def test_regression_server_must_exit_on_exception(
```

2022-04-22 03:51 UTC, tvainika submitted a review, later dismissed
There is still two commits in this branch, with one being empty commit [tests: fix integration tests flakiness](https://github.com/aiven/karapace/pull/390/commits/24f01ace39cf8918fd5b739e624de3bdee1fff77) Correctly applied rebase should eliminate that commit (with real changes) was merged in another PR

2022-04-25 05:33 UTC, tvainika approved these changes

2022-04-25 05:33 UTC, merged