poc: run integration tests within a podman pod
aiven/karapace pull request #403
Opened 2022-04-27 14:17 UTC by mhoffm-aiven

This PR is a POC to run integration tests within a podman pod

2022-05-02 08:19 UTC, hackaugusto commented on tests/conftest.py
> +    if kafka_bootstrap_servers is None:
There seems to be still an error:

```
E   ValueError: --kafka-bootstrap-servers and --kafka-version are incompatible options, only provide one of the two
```

2022-05-02 08:20 UTC, hackaugusto commented on tests/conftest.py
> -    if not re.match(VERSION_REGEX, kafka_version):
Now this is causing a lint error:

```
tests/conftest.py:6:1: F401 're' imported but unused
```

Please run `pre-commit` there are also some issues with the `.sh` file

2022-05-02 08:21 UTC, hackaugusto commented on scripts/integration.sh
> +#!/bin/bash
To properly test this, it should be enabled on the github actions, here:

https://github.com/aiven/karapace/blob/eb5a7720475b66de5011722db4799e3815fdacaa/.github/workflows/tests.yml#L41-L43

2022-05-03 04:58 UTC, tvainika requested changes
Didn't do deeper review, maybe this PR should have been opened in draft mode to not request reviews yet?

2022-05-03 05:50 UTC, mhoffm-aiven commented
> Didn't do deeper review, maybe this PR should have been opened in draft mode to not request reviews yet?

absolutely, sorry for the confusion

2023-03-02 08:31 UTC, jjaakola-aiven commented
I queried the status from @mhoffm-aiven and I am closing this as not relevant.

2023-03-02 08:31 UTC, closed without merging